"""Initial_DB

Revision ID: 271a26af3571
Revises: 
Create Date: 2024-03-23 12:54:01.898219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271a26af3571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheltter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheltter'))
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_src', sa.String(), nullable=True),
    sa.Column('url_adopt', sa.String(), nullable=True),
    sa.Column('sheltter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sheltter_id'], ['sheltter.id'], name=op.f('fk_pet_sheltter_id_sheltter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pet'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    op.drop_table('sheltter')
    # ### end Alembic commands ###
